### ISSUE TITLE
[Suggestion] 10連ガチャ

### ISSUE THREAD

**Issue by takasek** [watasuke/ichioshi-exchange-gacha#1]
ちょこちょこ回す楽しみとトレードオフなので悩ましいところですが、たくさんガチャ回したい欲もあります

**Comment by watasuke** [comment]
https://twitter.com/watasuke221/status/1063078954662223872
すいません！GitHubにコード反映してなかったんですが、リリースverではなんと！1回イチオシを投稿すると1万回ガチャが回せるようになってます！ :tada:
(Bitbucketで並行運用してて最新にそろえるの忘れてました……)

利用者がリリース直後から比べるとだいぶ落ち着いたので、このまま埋もれるのはもったいなくて出血大サービスした感じです。
あとでコードもアップしておきます。

**Comment by takasek** [comment]
あ、はい！
10000回のガチャ、堪能させていただいております。
ただ、ずいぶん回したのにまだ9783クレジットも残っており、1回1回アニメーションつきで回すのはなかなか大変だな…と思い提案させていただいた次第です。

**Comment by watasuke** [comment]
なるほど！それはだいぶ回されましたね……！
ハマっていただいたようでありがとうございます！

ただ10連ガチャは仕様がうまく思いついてないので保留とさせてください、すみません！

**Comment by watasuke** [comment]
やっぱりやります！仕様は思いついてないけど

**Comment by watasuke** [comment]
## 仕様
- 「10連ガチャ結果」みたいなページをつくる
    - 10cycle-fever
- 結果ごとにURLは生成せず使い切り
- イチオシタイトルをテキストリンクにして、個別イチオシページへの導線にする
- シェアボタンは置かない
- 単に10個通常と同じレイアウトでイチオシ羅列して、最後にガチャを引くボタンを通常と10連の2個置く

### 疑問 
- 1回ランダム1個抽出×10回やる？
- それとも1回ランダム抽出で10個のイチオシを取ってきて割り振る？
