### ISSUE TITLE
[Suggestion] イチオシコレクションにフィルタ機能

### ISSUE THREAD

**Issue by takasek** [watasuke/ichioshi-exchange-gacha#2]
- 自分が「へぇ〜」したもの
- 自分が「わかる」したもの
- この投稿者によるイチオシ

あたりがあると嬉しい気がします

**Comment by watasuke** [comment]
なるほどーたしかに。
必要最低限の機能で出しちゃいましたからね。

ただ私事をいうと、いままた別のプロダクトつくろうかとしちゃっててそっちに注力するためにイチオシ交換ガチャは置いておきそうな感じす、すみません(issueでいうことじゃない)
