### ISSUE TITLE
[表記揺れ] (ガチャコレクション|イチオシコレクション)

### ISSUE THREAD

**Issue by takasek** [watasuke/ichioshi-exchange-gacha#3]
おそらく「イチオシコレクション」が正？

https://github.com/watasuke/ichioshi-exchange-gacha/blob/a4722e10d5ac511f7f6c7e6b30f1ad63eec31f1e/app/views/shared/_header.html.erb#L15

**Comment by watasuke** [comment]
これは直しておきます！ありがとうございます！
